spring.application.name=easynotes

jwt.secretKey = au343g61#4$6278&83rgq7t1%^c8y3hx

logging.level.org.springframework=debug

spring.h2.console.enabled=true
spring.h2.console.path=/h2/console

spring.datasource.url=jdbc:h2:mem:notes

spring.jpa.show-sql=true
spring.jpa.defer-datasource-initialization=true